import Head from "next/head";
import { Inter } from "@next/font/google";
import { PropsWithChildren } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Main({ children }: PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Boards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
}
